[조회 성능 개선하기] 알리(허진호) 미션 제출합니다.
woowacourse/sql-tuning pull request #11
Opened 2021-10-13 09:15 UTC by jh8579

SQL에 많이 약해서 이번 미션은 진짜 힘들었네요 ㅜㅜ
좋은 피드백 많이 부탁드립니다!

[편하게 보기](https://github.com/jh8579/sql-tuning/blob/step1/README.md)

2021-10-17 06:38 UTC, DWL5 requested changes
안녕하세요 알리 수리입니다!!!

시간이 애매하게 나온 부분이 없어서 어떤 부분을 피드백 해야하는지..
어렵네요..
그래도 코드를 실행해보면서
몇가지 코멘트 남겨봤습니다!!
확인 부탁드릴게요!

2021-10-17 06:38 UTC, DWL5 commented on README.md
> +SELECT c.programmer_id, h.name AS "병원 이름"
SQL을 돌려보면 programmer_id가 null인 부분 까지 나오네요!

문제에서는 아래와 같이 되어있는데
```
 각 프로그래머별로 해당하는 병원 이름을 반환하세요. (covid.id, hospital.name)
```

programmer_id와 조인해서 covid.programmer_id에서 null로 나오는 부분을 없애줘야 할 것 같아요

2021-10-17 06:38 UTC, DWL5 commented on README.md
> +SELECT p.id AS programmer_id,
```
(covid.id, hospital.name, user.Hobby, user.DevType, user.YearsCoding)
```
문제에서는 위의 컬럼만 조회 하도록 되어있어요!

programmer_id와 covid.id가 조인되어서 사실 둘의 값도 같을 것 같아요!

```
FROM   subway.programmer p
         JOIN subway.covid c
              ON p.id = c.programmer_id
```

2021-10-17 06:38 UTC, DWL5 commented on README.md
> +CREATE INDEX `idx_cid_stay` ON `subway`.`covid` (hospital_id, member_id, programmer_id, stay);
인덱스의 이름이 조금 헷갈려요! 가장 선두에 있는 hospital_id를 명시하면 어떨까요?

밑의 문제에 Index에서는 `idx_cid_stay` 여기에 stay가 빠져있기도 하고요!

2021-10-17 06:38 UTC, DWL5 commented on README.md
> +CREATE INDEX `idx_cid_stay` ON `subway`.`covid` (hospital_id, member_id, programmer_id, stay);
오 programmer가 Index Range Scan에서, Unique Key LookUp으로 변경되네요
![image](https://user-images.githubusercontent.com/18106839/137614131-c3c59439-5899-4d7c-ac46-b407d59bcca9.png)

![image](https://user-images.githubusercontent.com/18106839/137614137-f2475dcd-4e41-459a-bca2-52e01f60013b.png)

2021-10-17 06:38 UTC, DWL5 commented on README.md
> +CREATE INDEX `idx_pid_country` ON `subway`.`programmer` (id, exercise(255));
여기도 인덱스 이름에 excercise가 들어가면 좋을 것 같아요!

2021-10-17 06:38 UTC, DWL5 commented on README.md
> +CREATE INDEX `idx_pid_country` ON `subway`.`programmer` (id, exercise(255));
programmer에 (id, exercise(255))와 (id), PK 걸고 테스트를 해봤는데요! 
이미 covid에서 join을 하면 join과 관련된 컬럼의 인덱스를 사용하는 것 같아요!
여기서는 아래 인덱스가 필요없지 않을까라는 생각도 들어요!
```
CREATE INDEX `idx_pid_country` ON `subway`.`programmer` (id, exercise(255));
```


![image](https://user-images.githubusercontent.com/18106839/137614364-3e73f2db-c73f-4b93-b5c3-77810e4617c6.png)

![image](https://user-images.githubusercontent.com/18106839/137614395-5e950718-8732-4e7a-afbd-924085fc1b50.png)

2021-10-18 09:03 UTC, jh8579 reviewed
피드백 주신 부분들 적용해봤습니다!
감사합니다!

2021-10-18 09:03 UTC, jh8579 commented on README.md
> +CREATE INDEX `idx_cid_stay` ON `subway`.`covid` (hospital_id, member_id, programmer_id, stay);
인덱스 이름이 조금 애매하네요 수정하겠습니다!

2021-10-18 09:03 UTC, jh8579 commented on README.md
> +CREATE INDEX `idx_pid_country` ON `subway`.`programmer` (id, exercise(255));
여기도 인덱스 이름 수정하겠습니다!

2021-10-18 09:03 UTC, jh8579 commented on README.md
> +CREATE INDEX `idx_pid_country` ON `subway`.`programmer` (id, exercise(255));
이번에 미션을 진행하면서 pk를 지정하는 것도 sql 성능에 영향을 미치는 것 같아서,
정확한 index의 효과만을 알고 싶어서 기존에 설정되어 있는 pk 이외에는 pk는 지정하지 않았습니다.

pk를 지정할 경우 해당 index가 필요하지 않을 수도 있겠네요!

2021-10-18 09:03 UTC, jh8579 commented on README.md
> +SELECT p.id AS programmer_id,
아 의미없는 컬럼을 조회하고 있었네요 수정하겠습니다!

2021-10-18 09:03 UTC, jh8579 commented on README.md
> +SELECT c.programmer_id, h.name AS "병원 이름"
아 null이 나오는 경우를 생각을 못했네요 수정하겠습니다!

2021-10-22 16:53 UTC, DWL5 approved these changes
알리!

피드백 잘 반영해 주셨어요!!
지금의 제가 더 이상 드릴 만한 피드백이 없네요 ㅜ

저도 미션에 대한 피드백을 반영하면서 혹시나 새로 알게 되는 내용이 있다면
피드백 더 드리도록 하겠습니다!

이번 미션 Approve 하겠습니다!!

2021-10-22 16:53 UTC, DWL5 commented on README.md
> +SELECT c.programmer_id, h.name AS "병원 이름"
이렇게 is not null인 부분만 가져오셨군요!!

2021-11-04 10:51 UTC, merged