[조회 성능 개선하기] 코다(김윤정) 미션 제출합니다.
woowacourse/sql-tuning pull request #15
Opened 2021-10-15 01:34 UTC by yjksw

안녕하세요 피케이 ~~!!! 
넘 오랜만이에요 !! ㅠㅠㅠ 루터 안가니 보기가 너무 힘든것....ㅠㅠㅠㅠ 잘 지내고 있죠? 
조회 성능 개선하기 미션 제출합니다 ㅎㅎ 
인덱스에 대해서 공부하면서 개선하려고 했는데,, 초반에 M1 이슈 때문에 시간 낭비를 많이 했어요 ㅠㅠㅠ 
그리고 인덱스에 대해서 나름 공부하고 쿼리를 짜도 옵티마이저의 실행계획이 예상치 못하게 나오기도 하더라구요 
아무래도 어려운 부분인 것 같습니다 ㅠㅠㅠ 

[편하게 보기 🙌](https://github.com/yjksw/sql-tuning/blob/step1/mission/query-tuning.md)
잘 봐주세요 !!!

2021-10-17 20:07 UTC, pkeugine requested changes
안녕하세요 코다!!! 오랜만이네요 🙌
저는 잘 지내고 있어요! 코다도 잘 지내고 계시겠죠? ㅎㅎ
미션을 너무 잘 진행해주셔서 리뷰하면서 오히려 제가 많이 배웠어요.
쿼리 자체를 잘 만들어주시기도 했고 리뷰하면서 제 미션을 진행하며 알지 못 했던 부분도 있었어요.

바로 머지 가능한 상황인데, 몇 가지 오타와 잘못된 사진이 있어서 그 부분만 수정하면 될 것 같아요 ㅋㅋㅋㅋㅋ
그리고 코멘트 몇 개 남겼으니 선택적으로 봐주세요!
고생하셨습니다!!! 👍

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +```
오 인덱스를 두 군데 적용해주셨네요 👍
부서관리자 테이블이 많은 정보를 담고 있지 않아서 (24개)
두 번째 인덱스는 적용해도 그리 큰 효과가 있을 것 같지 않아서 저는 적용하지 않았어요.
코다는 혹시 해당 인덱싱으로 성능이 향상되었나요?
저도 같은 부분을 고민해봐서 궁금한 마음에 코멘트 남겨요! 😁

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +```
쿼리문을 실행해봤는데 잘 작동하지 않네요!
작성하는 도중에 FROM 문을 SELECT 로 작성하신듯 해요 😁
큰 문제는 아니라서 그냥 수정하시면 되겠어요.

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +```
그나저나 이 방법 보고 놀랐어요!
제가 한 방식과는 다르게 하셨거든요. 'yes'랑 'no'를 각자 하나의 열로 만들다니 👍 👍 👍

코다의 쿼리를 가지고 이것저것 해봤는데, 형태를 크게 수정하지 않고 다음과 같이 서브쿼리를 없애고 시간을 줄여볼 수도 있더라구요. 큰 차이는 아니라서 시간 나시면 한 번 해봐도 좋을 것 같아요:

### 변경된 실행 계획
<img width="152" alt="Screen Shot 2021-10-18 at 12 54 35 AM" src="https://user-images.githubusercontent.com/48251668/137635059-3bb39549-89ba-4856-9551-266531abce35.png">

### 시간 측정
#### 이전
<img width="139" alt="Screen Shot 2021-10-18 at 12 51 26 AM" src="https://user-images.githubusercontent.com/48251668/137634916-a2b49d9c-9452-4453-8ff9-f20711297613.png">

#### 이후
<img width="133" alt="Screen Shot 2021-10-18 at 12 52 06 AM" src="https://user-images.githubusercontent.com/48251668/137634953-eac34797-f068-4637-9909-025a86657150.png">

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +<img width="164" alt="스크린샷 2021-10-14 오후 8 21 46" src="https://user-images.githubusercontent.com/63405904/137308109-b7d4e921-a108-4f17-9e90-0a46fc2b554d.png">
모두가 가천길병원으로 가는 중이군요 😂
이 결과 테이블은 인덱스를 적용 후에 찍으신 것 같아요 ㅋㅋㅋㅋ

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +```
쿼리 정말 잘 짜시네요 👍
보고 배웁니다!!

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +select covid.id, hospital.name, programmer.id, programmer.hobby, programmer.dev_type, programmer.years_coding
`covid.id`와 `programmer.id` 중 하나만 사용해도 괜찮겠네요! 😁

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +where hobby = 'Yes' and (student = 'Yes, part-time' or student = 'Yes, full-time' or years_coding = '0-2 years')
해당 개발자가 학생인지 아닌지 판단할 수 있는 기준이 두 개인데 programmer 테이블의 student 컬럼으로 판단하셨군요!

dev_type 컬럼에도 학생인지 아닌지가 적혀있는데, 어떤 것들은 dev_type 컬럼에서는 student 가 아닌데 student 컬럼에서는 Yes라고 되어있더라구요. 예를 들어 290번 친구.
<img width="1093" alt="Screen Shot 2021-10-18 at 2 34 30 AM" src="https://user-images.githubusercontent.com/48251668/137638472-1679181b-9da0-49c5-a336-d55682db034c.png">

개인적으로 이 두 컬럼의 정보가 일치하지 않는다면, student 컬럼을 이용해서 판단하는게 좋다고 생각합니다. 👍

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +CREATE INDEX idx_covid_hospital_id ON covid(hospital_id);
이 부분 코다 쿼리로 몇 가지 시도해봤는데요,
몇 가지 다른 컬럼을 추가해서 복합인덱스를 만들어보니 시간이 단축되네요!

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +CREATE INDEX idx_covid_hospital_id ON covid(hospital_id);
여기도 마찬가지로 복합 인덱스를 걸어주면 더 빠르게 쿼리를 수행하네요.

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +CREATE INDEX idx_covid_exercise ON covid(exercise);
covid가 아니라 programmer 일까요? 👀

2021-10-17 20:07 UTC, pkeugine commented on mission/query-tuning.md
> +- 시간 : 0.080 sec
인덱스 적용 전에는 몇 초였는지 궁금하네요 😁

2021-10-18 07:24 UTC, yjksw commented on mission/query-tuning.md
> +```
오옹 그랬군요 !! 
저는 성능 향상을 어떤 기준으로 봐야할지 모르겠더라구요... 
워크벤치에서 시간이 워낙 들쭉날쭉하게 (M1이라서 그런가) 나와서 어떨때는 실행계획의 query cost가 더 낮아도 더 시간이 오래 걸릴때도 있고,, ㅋㅋㅋ 
아무래도 못믿을만한거 같아서 저는 실행계획 테이블에 훑는 row수를 줄이는 방향으로 성능을 생각하기로 했어요!! 

테이블에 row 수는 적지만 일자순으로 범위를 두기 때문에 row수가 24 -> 9 개로 바뀌고 index range scan으로 실행계획이 변경되기는 했네요 ㅋㅋㅋ 그런데 full scan은 Random access를 안하니까 실제 성능에는 뭐가 더 좋을지 좀 애매하긴 한 것 같아요 !!
아마 테이블에 데이터가 많아지면 효과가 더 있지 않을까 싶습니당 👍

2021-10-18 07:24 UTC, yjksw commented on mission/query-tuning.md
> +```
ㅠㅠㅠ 요즘 왜 이렇게 덤벙대는지 ㅠㅠ 가을타나봐요

2021-10-18 07:36 UTC, yjksw commented on mission/query-tuning.md
> +<img width="164" alt="스크린샷 2021-10-14 오후 8 21 46" src="https://user-images.githubusercontent.com/63405904/137308109-b7d4e921-a108-4f17-9e90-0a46fc2b554d.png">
ㅋㅋㅋㅋ 인덱스 넣었다가 빼는게 넘 힘드네요 ,,

2021-10-18 07:37 UTC, yjksw commented on mission/query-tuning.md
> +select covid.id, hospital.name, programmer.id, programmer.hobby, programmer.dev_type, programmer.years_coding
오오 그러네요 !!!

2021-10-18 07:38 UTC, yjksw commented on mission/query-tuning.md
> +where hobby = 'Yes' and (student = 'Yes, part-time' or student = 'Yes, full-time' or years_coding = '0-2 years')
데이터가 좀 이상한게 많더라구요 ,, ㅋㅋㅋㅋ 감삼당 !! 😆

2021-10-18 07:38 UTC, yjksw commented on mission/query-tuning.md
> +CREATE INDEX idx_covid_exercise ON covid(exercise);
맞아여 ㅋㅋㅋㅋ 매의눈 !!

2021-10-18 08:21 UTC, yjksw commented on mission/query-tuning.md
> +CREATE INDEX idx_covid_hospital_id ON covid(hospital_id);
오오 어떤 칼럼을 추가했나요 ?! 
저는 covid에 hospital_id, member_id, stay 복합인덱스를 만들었었는데
각기 조건절에 따로 걸리다 보니 실행계획을 봤을때 인덱스를 안타는 것 같더라구요 .. ㅠㅠ 제가 잘 몰라서 그런걸수도 있지만 ..ㅎㅎ
제 노트북에 ec2 연결해서 돌리고 있어서 그런가 실행시간에 자꾸 왔다갔다해서 (크게는 0.4 정도도 차이가 나요 ..ㅠ) 실행계획으로 더 나아졌는지 확인하고 있는데 제가 건 복합인덱스는 훑는 row 수나 타는 인덱스, query cost 차이가 없더라구요 ..
아 위에 빼먹었는데 covid.member_id도 인덱스로 추가했었어요 !! 

혹시 피케이는 어떻게 수정했나요 ?!

2021-10-18 08:21 UTC, yjksw commented on mission/query-tuning.md
> +CREATE INDEX idx_covid_hospital_id ON covid(hospital_id);
위 쿼리랑 비슷한 상황일꺼 같은데 .... 궁금하네요 !! ㅋㅋㅋ

2021-10-18 08:23 UTC, yjksw commented on mission/query-tuning.md
> +- 시간 : 0.080 sec
위에 쿼리랑 거의 비슷하게 동작했어요 ~!! 거의 인덱스도 비슷하게 걸려서 바로 찍어서 결과만 제출했슴당,,ㅋㅋㅋㅋㅋ

2021-10-18 08:31 UTC, yjksw commented on mission/query-tuning.md
> +```
엇 서브쿼리를 삭제하고도 칼럼을 나눌 수 있나요 ...?! 
아니면 결과 테이블이 조금 다른 형식으로 바뀌나요 ??? 
어렵네용, ,,ㅋㅋㅋㅋㅋ 피케이 능력자...

2021-10-18 08:44 UTC, yjksw commented
피케이~~~!!
생각할 거리를 많이 던져주어서 고민 많이하면서 배웠어요 !!
그런데 피케이가 던져준 문제를 하나도 못 푼거 같다는... ㅋㅋㅋㅋㅋ

미션을 하면서 어느 기준으로 향상되었다고 해야할지 너무 애매하더라구요 ㅠㅠ 특히 크게 시간 차이나 나지 않으면 어떻게 더 나아졌다고 해야할지 고민이구,, 
또 복합인덱스를 걸었을 때 안탈꺼 같은 부분들도 인덱스를 걸어야할지도 고민 포인트 였습니다 !!
마지막으로 select 하는 칼럼을 인덱스로 추가하면 실행계획에서 커버링 Index를 하여 조회시 실행계획이 예쁘게 나오긴 하는데 얼만큼의 성능 향상이 있는지 확인하기도 어렵더라구요 .. ㅋㅋㅋ (삽입시 성능 저하가 있을 것 같아서요 !!) 

고민할 포인트가 많네요 !! ㅠㅠ
피케이 의견 궁금합니다 ..ㅎㅎㅎ !!

2021-10-22 11:59 UTC, pkeugine commented on mission/query-tuning.md
> +```
오오 그렇군요!!!
맞아요 저도 M1이 아닌데 실행계획 query cost가 더 낮아도 시간이 더 오래 걸릴 때가 있더라구요?
그래서 아직 배울게 많은 것 같다는 생각을 했어요 ㅋㅋㅋ
설명 감사합니다 👍👍

2021-10-22 12:25 UTC, pkeugine commented on mission/query-tuning.md
> +```
아 그냥 저도 sql을 잘 다루지 못 해서 이것저것 해보다가 발견했어요 ㅋㅋㅋ
```sql
select 
round(count(if(hobby = 'Yes', 1, null)) / count(*) * 100, 2) as yes,
round(count(if(hobby = 'No', 1, null)) / count(*) * 100, 2) as no
from programmer;
```
최대한 코다의 결과 테이블을 유지해보려고 했어요.
이 때 if 문을 쓰면 위 코멘트의 결과가 나오더라구요 😁

능력자라고 하기엔 제가 짠 쿼리보다 코다 쿼리가 성능이 더 좋아요 ㅎ

2021-10-22 13:06 UTC, pkeugine commented on mission/query-tuning.md
> +CREATE INDEX idx_covid_hospital_id ON covid(hospital_id);
저는 covid 테이블에서 다른 인덱스를 따로 하지 않고 hospital_id 와 member_id 복합 인덱스를 걸어줬어요.
리뷰 남기기까지 시간이 좀 걸린게... 이게 왜 성능이 좋아지는지 명확하지 않아서입니다...
처음에는 member_id, hospital_id 순으로 복합 인덱스를 걸어줬어요. 왜냐하면 member_id 의 카디널리티가 더 크니까요.
그런데 시간이 더 오래 걸리더라구요.
혹시나 해서 hospital_id 를 먼저 해서 걸어주니 시간이 단축되었습니다 ㅋㅋㅋ 카디널리티가 크다고 해서 꼭 먼저 걸어주는게 답은 아닌가봐요 🤔

2021-10-22 13:12 UTC, pkeugine commented on mission/query-tuning.md
> +CREATE INDEX idx_covid_hospital_id ON covid(hospital_id);
맞아요! 여기서도 똑같이 hospital_id 와 member_id 복합 인덱스를 걸었어요 😁
<img width="827" alt="Screen Shot 2021-10-22 at 10 11 57 PM" src="https://user-images.githubusercontent.com/48251668/138459304-5b1f7b71-be3d-4b6c-8b2d-2a2591dbef6e.png">

### 결과
#### 이전
<img width="141" alt="Screen Shot 2021-10-22 at 10 12 24 PM" src="https://user-images.githubusercontent.com/48251668/138459362-f9fe00a9-af86-4744-b442-16e05ee66915.png">

#### 이후
<img width="134" alt="Screen Shot 2021-10-22 at 10 12 40 PM" src="https://user-images.githubusercontent.com/48251668/138459405-ff9c7f5e-7ac4-4b7d-abf5-8b1ad8e8d252.png">

2021-10-22 13:40 UTC, pkeugine approved these changes
코다!!! 댓글 남겨주신 부분 다 확인했습니다.
그리고 코다의 쿼리를 다시 한 번 확인하면서 좋은 쿼리로 복습도 하고 정말 좋았어요.

그리고 맞아요... 저도 어느정도까지 해야 성능이 좋아졌다고 할 수 있는지 아직 애매해요.
지금 저는 최우선적으로 목표한 시간 이하로 속도가 단축되었는지를 확인해요.
그리고 코다에게 리뷰로 시간을 0.005초 정도 줄여보라는 리뷰를 남기긴 했지만...  저도 시간 차이가 크게 나지 않으면 확실한 개선이라고 말하기도 뭐해서 사실 그리 필수적인 단축은 아니라고 생각해요. (물론 단축이긴 하니까 좋긴 좋죠) 그냥 서브쿼리 없애볼겸 해본 느낌? 😁

물론 아직 배울 점이 많아서 지금 이런 생각이 다 맞진 않겠지만, 저도 복합인덱스 걸었을 때 안 탄다 싶으면 그냥 뺐어요. 그리고 복합인덱스는 아직 어렵더라구요. 카디널리티를 고려해서 복합 인덱스의 순서를 결정해도 막상 시간이 더 오래 걸리는 경우도 있었구요. 커버링 인덱스의 경우는 그걸 사용하는 이유가 결국 성능 개선인데, 성능 개선을 확인하기 어렵다면 코다 말대로 삽입시 오히려 성능 저하가 생길 수도 있을 것 같아서 안 쓰는게 좋지 않을까 싶네요.

덕분에 리뷰하면서 저도 이런저런 생각을 해보고 많이 배우네요!
고생하셨습니다. 어프루브할게요!! 다음 미션도 파이팅입니다 💪💪💪

2021-10-23 05:51 UTC, yjksw commented on mission/query-tuning.md
> +CREATE INDEX idx_covid_hospital_id ON covid(hospital_id);
오ㅏ..........진짜 짱 !! ㅠㅠㅠ 시간 차이가 어마어마 하네요 !!!

2021-10-23 05:52 UTC, yjksw commented on mission/query-tuning.md
> +CREATE INDEX idx_covid_hospital_id ON covid(hospital_id);
역시 ㅠㅠㅠ 어렵군요 !! 같이 고민해보니까 좋네요 😊

2021-10-24 13:25 UTC, merged