[조회 성능 개선하기] 손너잘(손민성) 미션 제출합니다.
woowacourse/sql-tuning pull request #23
Opened 2021-10-16 10:10 UTC by bperhaps

너무!! 어려워요!! 도와주세요!!!! 글에 무엇일까...? 하는 내용들이 저의 질문들입니다ㅜㅜ
함께 고민해주세요ㅜㅜ 리뷰... 감사합니다!!! 잘 부탁드려요!

2021-10-19 11:29 UTC, hsik0225 requested changes
### 안녕하세요 손너잘
이것저것 하다보니 리뷰가 늦어졌네요. 오래 기다리게 해서 죄송합니다 😅

너잘이 작성한 리드미 잘 읽었습니다!
만난 이슈와 해결 과정 등을 자세하게 적어주셔서 너잘이 어떤 방식으로 문제를 풀어나갔는지 알 수 있어서 좋았어요. 제가 DB 인덱스가 처음이라서 잘 몰랐는데 너잘이 상세하게 작성해주셔서 보면서 많이 배울 수 있었네요.

인덱스 적용은 너무 잘해주셔서 쿼리 위주로 살펴보았습니다.
확인 부탁드릴게요 😄

2021-10-19 11:29 UTC, hsik0225 commented on README.md
> +부서관리자, 급여, 직급의 종료일자에 인덱스를 걸고, 사원, 부서는 primary키를 이용, 사원 출입기록은 (사원번호, 입출입구분)으로 걸어줬는데 왜 60정도로 나오는지 ㅜㅜ 50 아래로는 안내려가네요... 이유가 뭘까요..?
손너잘이 설명한대로 제 MAC에서 실행했을 때는 2ms라는 어마무시한 스피드로 결과가 나오네요.
제가 구현했던 것보다 2배는 빠른 속도라서 감탄만 나왔습니다.

![스크린샷 2021-10-19 오후 6 39 54](https://user-images.githubusercontent.com/56301069/137884882-6c8956dc-a229-4dc1-bb80-37a92a894e49.png)

단순 컴퓨터 성능 차이 때문일까요?
이유는 잘 모르겠네요.. 😥

2021-10-19 11:29 UTC, hsik0225 commented on README.md
> +또한 hobby의 no와 yes의 비율을 생각해 보자, no가 압도적으로 적은것을 알 수 있다. 이를 확용하면 아래와 같은 쿼리를 만들 수 있다.
`no`가 `yes`에 비해 적으니 `no`만을 찾는다면 `yes`를 같이 찾을 때보다 계산량이 굉장히 줄어드네요!
아이디어가 굉장히 좋네요. 이래서 알고리즘을 해야하는 걸까요? 😄

한 가지 궁금한 점으로 아래에서 max(id)를 따로 서브 쿼리로 찾으신 이유가 있을까요?

같은 programmer 테이블의 id를 이용한 함수 max(id) 를 사용하는거라면 서브 쿼리가 아닌 함수만을 사용해도 괜찮지 않을까요?

```sql
select
(100 - (round(count(hobby) / max(id) * 100, 1))) as yes,
round(count(hobby) / max(id) * 100, 1) as no
from programmer
where hobby = 'no';
```

제 컴퓨터 기준으로 서브쿼리를 사용하지 않으니 약 3배 정도 빨라졌네요!

### 서브쿼리 사용
![스크린샷 2021-10-19 오후 7 07 40](https://user-images.githubusercontent.com/56301069/137889255-090a87c4-48ff-47b1-99f1-62dff32f3bfa.png)

### 서브쿼리 미사용
![스크린샷 2021-10-19 오후 7 07 49](https://user-images.githubusercontent.com/56301069/137889250-99f289a7-9ad0-45e6-a8c2-2066cb015121.png)

2021-10-19 11:29 UTC, hsik0225 commented on README.md
> +문제가 잘못되어 있는 것 같아 ([programmer.i](http://programmer.id)d, [hospital.name](http://hospital.name))으로 수정한다.
이 문장을 보고 마치 교수님에게 "시험 문제에 오류가 있는 것 같습니다." 라고 이야기하는 듯한 느낌이 들어서 재밌었어요.
주어진 문제를 그대로 받아들이지 않고, 문제 자체를 의심하는 자세가 멋있네요 👍

2021-10-19 11:29 UTC, hsik0225 commented on README.md
> +
현재 쿼리가 `programmer_id` 가 `null` 일 경우도 같이 반환하고 있는데요.
`프로그래머 별 병원 이름 반환`이 요구 사항이므로 programmer_id가 null 인 경우는 결과에서 제외해야 하지 않을까 생각이 드네요.

> programmer_id가 null인 사용자의 병원 이름은 `~~~`입니다, 

라는 결과가 어색하게 느껴지네요.

2021-11-01 16:37 UTC, bperhaps commented on README.md
> +또한 hobby의 no와 yes의 비율을 생각해 보자, no가 압도적으로 적은것을 알 수 있다. 이를 확용하면 아래와 같은 쿼리를 만들 수 있다.
아 정말 그렇네요..!!! 감사합니다!!

2021-11-01 16:40 UTC, bperhaps commented on README.md
> +
```
select straight_join c.programmer_id, h.name from hospital h
inner join covid c
on h.id = c.hospital_id
where c.programmer_id is not null
```

위와 같은 방식으로 변경하였습니다!

2021-11-03 13:39 UTC, hsik0225 approved these changes
안녕하세요 너잘
피드백 반영 확인했습니다.
이번 리뷰를 하면서 너잘이 상세하게 작성해주신 노션을 보면서 많이 배울 수 있어서 좋았어요.
미션 수고하셨고, 남은 우테코 기간 화이팅입니다!

2021-11-03 13:39 UTC, merged