[조회 성능 개선하기] 케빈(박진홍) 미션 제출합니다.
woowacourse/sql-tuning pull request #3
Opened 2021-10-11 08:21 UTC by xlffm3

2021-10-17 05:57 UTC, bperhaps requested changes
안녕하세요 케빈!!! 못하는게 뭐냐?
제 쿼리랑 크게 다른점이 없어서 딱히 흠잡을곳은 없네요..!
몇가지 내용을 남겨봤는데 도움이 됐으면 좋겠어요!!
인덱스는 전체적으로 봤는데 딱히 필요 없는 인덱스는 없는것같아요.
첫번쨰 문제는 실행이 안되는 문제가 있는데 확인 한번만 부탁드려요!

2021-10-17 05:57 UTC, bperhaps commented on Assignment.md
> +```
해당 쿼리문을 실행하면 group by로 인해서 쿼리 에러가 발생합니다.
확인 한번만 부탁드려요! 전체적인 쿼리는 저랑 동일한것 같아서 드릴 말씀이 없나요.!

2021-10-17 05:57 UTC, bperhaps commented on Assignment.md
> +* 인덱스 적용 후, 50ms 보다 낮은 15~16ms를 기록했습니다.
제 컴퓨터에서는 60ms정도를 기록하네요.. 저도 이 아래로 줄이지 못해서 슬펏는데 결국 컴바컴인건가...
개인적으로 이부분에서는 성능을 미약하게나마 더 올릴 부분이 있다고 생각하는데요, 사원번호와 입출입구분을 복합인덱스로 잡으면 조금 더 빨라진답니다. 사원번호의 카디널리티가 1이므로 (사원번호, 입출입구분)으로 잡으면 되구, 이렇게 하면 복합인덱스 = 'O' 를 추출할 때 인덱스를 활용할 수 있게됩니다!

2021-10-17 05:57 UTC, bperhaps commented on Assignment.md
> +  * OR 조건이 존재하면 쿼리가 인덱스를 타지 않는다고 해서, 실제로 테스트해보니 hobby, dev_type, years_coding_prof에 대해 인덱스를 걸어도 성능이 동일하네요. :(
이 부분에 대해서 저도 조사를 조금 했었는데제가 작성한걸 공유해드릴께요!


### 이 문제는 인덱싱을 통한 쿼리 최적화에 한계가 있다.

기본적으로 이 문제는 join을 위한 인덱싱 이외에는 쿼리 최적화에 한계가 있다고 생각합니다.

쿼리 최적화를 수행해야하는 부분은 where절에 걸리는 programmer와 관련된 컬럼들과 관련이 있다. where절을 확인하면 hobby, years_coding, dev_type에 대한 조건을 걸어주는것을 확인할 수 있다.

일단, id를 기준으로 정렬하는것은 id를 pk로 잡음으로서 클러스터링 인덱스를 활용하여 order 비용을 제거할 수 있다.

hobby와 years_coding 도 마찬가지이다. 만일 dev_type 조건이 없다면은 복합인덱스와 커버링 인덱스틑 통해서 최적화가 가능했을 것이다. 하지만 문제는 dev_type에 있다. devt_type은 text형식이기 때문에 인덱싱이 불가능하며 인덱싱이 가능하더라도 들어가 있는 데이터의 형식이 제각각이므로 `"%student%"` 를 이용할수밖에 없다.

스토리지 엔진은 기본적으로 where 조건절에서 index를 사용할 수 있는 데이터를 테이블에서 추출한다. 그리고 mysql 엔진은 추출된 데이터에서 인덱스가 아닌 컬럼에 대하여 추출한다.

하지만 현재 필요한 쿼리를 보면 or가 들어가 있다. 이것은 즉, hobby, years_coding에 대해서 인덱스를 걸었더라도 or dev_type으로 인해 결국 인덱스를 활용하지 못하게 된다는 것을 의미한다.

![image](https://user-images.githubusercontent.com/33603557/137613463-455080d2-72ca-4dc3-b4fe-7c992f4178f2.png)

현재 hobby와 years_coding으로 복합인덱스를 걸어놓으 상태이다. 그럼에도 인덱스 풀 스캔을 사용하는것을 알 수 있다.

그렇다면 or을 and로 바꿔보자.

![image](https://user-images.githubusercontent.com/33603557/137613455-e1a170ce-3c66-417e-93a2-ed7f7687194e.png)


type이 range, 즉 레인지 스캔을 이용함과 동시에 (hobby, years_coding) 인덱스를 사용할 수 있음으로 인덱스 푸시 다운과 using where을 이용하는것을 볼 수 있다. and의 경우는 인덱스를 이용하여 hobby, years_coding과 관려된 row를 뽑아낼 수 있기 때문에 이러한 결과가 나오는 것이다.

따라서 이 경우는 따로 인덱스를 걸지 않더라도(pk와 join 제외) 성능을 만족시킬 수 있다.

2021-10-17 05:57 UTC, bperhaps commented on Assignment.md
> +* 개인적으로 hospital 컬럼 속성을 변경하지 않고 문제를 해결해보고 싶었는데, 성능 요구사항을 충족하기 어려워서 변경했습니다.
컬럼 속성을 text로 바꾸고 진행해도 충분히 속도가 나오는데유..??
order by null을 group by 뒤에 붙여서 filesort를 제거할 수 있습니다. mysql만의 문법입니다. 다른 dbms에서는 동작하지 않습니다. 요구사항에 정렬 조건이 없으니 적용하셔도 좋을 것 같습니다!

2021-10-19 07:53 UTC, xlffm3 commented on Assignment.md
> +```
생각해보니 group by가 필요없어서 제거했습니다.

2021-10-19 07:53 UTC, xlffm3 commented on Assignment.md
> +* 인덱스 적용 후, 50ms 보다 낮은 15~16ms를 기록했습니다.
오호, 

![image](https://user-images.githubusercontent.com/56240505/137866020-67b71b84-1900-4d6a-a0ac-0b0033cfa034.png)

전

![image](https://user-images.githubusercontent.com/56240505/137866093-00ddeb20-2d89-404c-b85f-326843a7ab5a.png)

후

조금 더 개선되네요!

2021-10-19 07:58 UTC, xlffm3 commented on Assignment.md
> +* 개인적으로 hospital 컬럼 속성을 변경하지 않고 문제를 해결해보고 싶었는데, 성능 요구사항을 충족하기 어려워서 변경했습니다.
지금 보니 병원 이름에 인덱스 없어도 잘 되네요. 말씀대로 order by null 적용하니 filesort가 사라지네요!

2021-10-20 15:36 UTC, bperhaps approved these changes
안녕하세요 케빈~ 반영하신 부분 잘 확인 했습니다!
제가 더 공부해서 좋은 리뷰를 드렸어야 했는데 요즘 이리 치이고 저리 치이고 하다보다 생각보다 학습량을 늘리는게 쉽지가 않네요 ㅠㅠ
정말 수고하셨습니다 머지하겠습니다!

2021-10-28 13:21 UTC, merged