[조회 성능 개선하기] 멍토(김유기) 미션 제출합니다.
woowacourse/sql-tuning pull request #4
Opened 2021-10-11 13:22 UTC by daum7766

안녕하세요 코다! 멍토입니다.

작업은 윈도우에서 진행했습니다.
(그래서 작업 환경에 따라서 속도는 다르게 나올 수 있습니다.)

![image](https://user-images.githubusercontent.com/45873044/136797097-5a9e8580-09ac-4e7e-840c-088dcfa8257f.png)
이렇게 알고있었는데 테스트를 해보면서 특정한 경우는 따로 만들어야 코스트가 줄어드는 현상을 확인했습니다.
이건 따로 공부를 해봐야 할거같아요.
혹시 왜그런지 아시면 알려주세요 ㅎㅎ

최대한 여러가지 테스트를 해보며 진행했는데 계속 수정해서 인덱스 추가부분이 틀렸을 수 있어요.
테스트 하는데 결과가 다르게 나오면 연락주세요!

감사합니다.

2021-10-16 14:32 UTC, yjksw requested changes
안녕하세요 멍토~~!! 코다입니다 🙌
작성해주신 쿼리 잘 확인했어요 !! 정말 깔끔하게 잘 짜시더라구요,, ㅎㅎ
복합인덱스를 정말 잘 활용하시는 것 같아요 !! 

피드백은....큰 도움이 될지 모르겠고 ㅎㅎ 
저도 잘 모르는 입장이라서 물어보고 싶은 것들 위주로 코멘트 한 것 같네요 !! 
한번 확인해 주세요 🚀

갑자기 추워졌는데 감기 조심하세요 ~!!

2021-10-16 14:32 UTC, yjksw commented on result.md
> +covid -> (hospital_id, programmer_id,)
`is not null` 로 비교할 경우도 인덱스를 타나요???

2021-10-16 14:32 UTC, yjksw commented on result.md
> +) as covid_info
`서브쿼리보단 조인문을 활용하세요` 라고 하던데 이 부분이 단순 조인보다 서브쿼리로 있으면 좋은 이유가 있나요 ?

2021-10-16 14:32 UTC, yjksw commented on result.md
> +covid -> (programmer_id, hospital_id)
각각 on 절과 where 절에 각각 사용되는데 복합 인덱스로 거는 것과 각기 인덱스로 거는 것은 어떤 차이가 있을까요 ? (저도 잘 몰라서 고민하다가 코멘트 남깁니다..ㅎㅎ😅)

혹시 이 부분에 의해 문제 요구사항에 있는 programmer.id 순으로 정렬 (문제에는 user.id라고 적혀있지만) 하는 부분이 충족되는 것일까요?

2021-10-16 14:32 UTC, yjksw commented on result.md
> +and (dev_type like '%Student%'
저는 요것이 programmer의 Student 칼럼을 살피는 거라고 생각했는데 dev_type에도 있군요 !! 
사소한 거라서 쿼리가 크게 바뀔거 같지는 않네요 ..ㅎㅎ 
다만 student 칼럼으로 조건을 걸면 Like를 사용하지 않아도 될수도..?있다고 생각해요

2021-10-17 13:53 UTC, daum7766 commented on result.md
> +and (dev_type like '%Student%'
요구사항에 보면 이러한 내용이 있습니다. 
프로그래밍이 취미인 학생 혹은 주니어(0-2년)들이 다닌 병원 이름을 반환하고 user.id 기준으로 정렬하세요. (covid.id, hospital.name, user.Hobby, user.DevType, user.YearsCoding)
문제 뒤에 있는 컬럼을 가지고 쿼리를 작성하라고 이해를 했고 그로 인해 dev_tyep을 이용했습니다.

2021-10-17 14:43 UTC, daum7766 commented on result.md
> +) as covid_info
조인을 할때 row의 개수를 줄이기 위해 서브쿼리를 쓴것이지만
위에서는 조인으로 바꿔도 이상이 없는걸로 알고있습니다.

2021-10-17 14:43 UTC, daum7766 commented on result.md
> +covid -> (programmer_id, hospital_id)
전부 on절에서 사용을 하고 있다고 정정을 하고 시작하겠습니다.(where로 변경해도 같긴 합니다)
복합인덱스를 사용하면 장점은 앞에 조건에 일치한 데이터를 가지고 뒤에서 또 사용하기 때문에 여러가지 조건이 일치하는 경우는 효율이 더 좋은걸로 알고 있습니다.

여기서는 hospital_id를 왜 걸었는지 생각이 나지는 않네요
테스트를 할 수 있을때 확인해 보겠습니다.

정렬에 관련된 이야기를 하면 이거는 복합이 아니어도 똑같이 동작할 것이라 생각합니다.
현재 테스트할 환경이 아니어서 확인은 못하네요 ㅜㅠ
(order by에는 없지만 인덱스로 정렬해서 사용하고 있다고 이해하시면 될 것 같습니다.)

2021-10-17 14:43 UTC, daum7766 commented on result.md
> +covid -> (hospital_id, programmer_id,)
부정형 비교는 인덱스를 사용하지 않는걸로 알고 있습니다.
저기서 is not null 사용한 이유는 programmer_id와 join 하는것보다
비용이 싸다고 판단되어 사용한 것입니다.

2021-10-18 07:09 UTC, yjksw commented on result.md
> +covid -> (hospital_id, programmer_id,)
맞아요 ~!! 제가 궁금했던 이유는 그럼에도 불구하고 복합인덱스에 programmer_id를 넣은 이유에요 ㅎㅎ 
select 절에 있기 때문일까요 ?! 
저도 좋다고 생각하지만 삽입시 성능도 함께 생각해본다면 무엇이 더 좋을지 헷갈리네여 ..ㅎㅎ 멍토의 의견이 궁금했습니다 !!

2021-10-18 07:10 UTC, yjksw commented on result.md
> +covid -> (programmer_id, hospital_id)
굳 좋아요 ~!! 복합인덱스를 걸때와 각기 인덱스를 걸때 비용 차이가 있는지 궁금하네요 ,,ㅎㅎ

2021-10-18 07:16 UTC, yjksw approved these changes
안녕하세요 멍토 ~~!! 미션 잘 진행해주셨어요 ㅎㅎ
저랑 다르게 복합인덱스도 잘 활용하고 서브쿼리로 row수도 줄이고 그래서 많이 배웠슴당 ㅎㅎ
멍토의 쿼리를 보면서 시야가 더 넓어진 것 같아요 !! 
그냥 사소한 의견 몇개 더 남기고 approve 합니다. 

수고했어요 !! 🙌👍

2021-10-31 13:49 UTC, daum7766 commented on result.md
> +covid -> (hospital_id, programmer_id,)
인덱스의 사이즈는 hospital_id * prorammer_id 만큼 사이즈가 생길거에요.
실제 성능상의 문제가 발생하는지는 따로 테스트를 해봐야 확인이 가능할 것 같네요.
여기서는 Select의 비용을 어떻게 줄일지 중점적으로 생각했었어요

2021-10-31 13:50 UTC, daum7766 commented on result.md
> +covid -> (programmer_id, hospital_id)
복합인덱스를 걸면 정렬이 되어있는 상태에서 두번째 조건으로 정렬이 되어있기 때문에 연속적으로 조건이 들어가면 성능상 이점이 있는걸로 알고있어요.

2021-10-31 13:53 UTC, merged